version: '3.9'

networks:
  rabbitmq_go_net:
    driver: bridge

services:
  # ActiveMQ
  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports:
      - 1883:1883 # mqtt
      - 8161:8161 # ui
      - 61613:61613 # stomp
      - 61614:61614 # ws
      - 61616:61616 # jms
    volumes:
      - ~/Documents/data/activemq/data:/data/activemq
      - ~/Documents/data/activemq/log:/var/log/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=username
      - ACTIVEMQ_ADMIN_PASSWORD=password
    healthcheck:
      test: ['CMD', 'nc', '-vz', 'localhost', '8161']
      interval: 5s
      timeout: 5s
      retries: 5
  # Kafka
  zookeeper:
    restart: unless-stopped
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    expose:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    restart: unless-stopped
    image: confluentinc/cp-kafka
    container_name: kafka
    hostname: kafka
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - zookeeper
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672 # amqp
      - 15672:15672 # amqp
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  # Redis
  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
