cacheFolder: "./.yarn/cache"

cloneConcurrency: 2

defaultLanguageName: "node"

enableColors: true

enableConstraintsChecks: true

enableGlobalCache: true

enableProgressBars: true

enableStrictSsl: true

httpRetry: 6

httpTimeout: 60000

initScope: "yarnpkg"

init-version: "0.0.1"

init-license: "GPL-3.0"

preferInteractive: true

registry: "https://registry.yarnpkg.com"

strict-ssl: true

telemetryUserId: yarnpkg/berry
