version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres-data:
    image: postgres:latest
    container_name: postgres-data
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  redis-data:
    image: redis:latest
    container_name: redis-data
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
