version: '3.9'

volumes:
  cockroach_data:
    driver: local
  mongodb_data:
    driver: local
  postgres_data:
    driver: local

services:
  cockroachdb-database:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroachdb-database
    restart: always
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure

  postgres-database:
    restart: unless-stopped
    image: postgres:latest
    container_name: postgres-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  mongo-database:
    image: mongo:7-jammy
    container_name: mongo-database
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

  mysql-database:
    image: mysql:8.2.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  redis-cache:
    restart: unless-stopped
    image: redis:latest
    container_name: redis-cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
