version: '3.9'

networks:
  rabbitmq_go_net:
    driver: bridge

services:
  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports:
      - 1883:1883 # mqtt
      - 8161:8161 # ui
      - 61613:61613 # stomp
      - 61614:61614 # ws
      - 61616:61616 # jms
    volumes:
      - ~/Documents/data/activemq/data:/data/activemq
      - ~/Documents/data/activemq/log:/var/log/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=username
      - ACTIVEMQ_ADMIN_PASSWORD=password
    healthcheck:
      test: ['CMD', 'nc', '-vz', 'localhost', '8161']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672 # amqp
      - 15672:15672 # amqp
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
