version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres-database:
    restart: unless-stopped
    image: postgres:latest
    container_name: postgres-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  mysql-database:
    image: mysql:8.2.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
