version: '3.9'

services:
  redis-cache:
    restart: unless-stopped
    image: redis:latest
    container_name: redis-cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
