version: '3.9'

services:
  cache-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: cache-redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  cache-memcached:
    restart: unless-stopped
    image: memcached:latest
    container_name: cache-memcached
    ports:
      - 11211:11211
