openapi: 3.0.0
paths:
  /health:
    get:
      operationId: HealthController_getStatus
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Health
info:
  title: Nest.js
  description: Nest.js Extensions
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas: {}
