name: Continuous Integration / Continuous Delivery

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**
      - dependabot/**

jobs:
  lint:
    name: CI / CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --network-timeout 86400000
      - name: Linting
        run: pnpm lint
      - name: Unit Test
        run: pnpm test --concurrency 1
      - name: Build Production
        run: pnpm build --concurrency 1
