name: Go - Continuous Integration

on:
  push:
    branches:
      - "master"
      - "develop"
      - "hotfix/**"
      - "feature/**"
      - "renovate/**"
      - "dependabot/**"
    paths:
      - "languages/go/**"

jobs:
  ci:
    name: Go - Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - name: Format
        run: go fmt
        working-directory: "./languages/go"
