name: Continuous Integration / Continuous Delivery

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**
      - dependabot/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
      - name: Linting
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
      - name: Unit Test
        run: yarn test --concurrency 1

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
      - name: Build Production
        run: yarn build --concurrency 1
