name: Chess - Sync Games

on:
  push:
    branches:
      - "master"
    paths:
      - "languages/typescript/apps/web/scripts/ts/chess/import/**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    name: Sync Games
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: "languages/typescript/apps/web"
          sparse-checkout-cone-mode: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
        working-directory: languages/typescript/apps/web
      - name: Set Up Prisma
        run: pnpm prisma format && pnpm prisma generate
        working-directory: languages/typescript/apps/web
      # - name: Sync Games
      #   run: pnpm ts-node ./scripts/ts/chess/import/games.ts
      #   working-directory: languages/typescript/apps/web
      #   env:
      #     POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
