name: Node.js - Continuous Integration - Continuous Delivery

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**
      - dependabot/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.0"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
        working-directory: typescript
      - name: Linting
        run: yarn lint
        working-directory: typescript
      - name: Unit Test
        run: yarn test
        working-directory: typescript
      - name: Build Production
        run: yarn build
        working-directory: typescript
